name: tester
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pip
  - jupyterlab
  - notebook
  - pandas
  - matplotlib
  - dowhy
  - causalimpact
  - causalinference
  - medil[all]        # MeDILL
  - seaborn           # MeDILL
  - pytorch_lightning # MeDILL
  - pyagrum
  - prettytable
