name: cdut
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pip
  - jupyterlab
  - notebook
  - pandas
  - matplotlib
  - networkx
  - pyagrum
  - tabulate
  - termcolor
  - pip:
      - pgmpy
